---
- name: Configure an iSamples Development server
  hosts: all
  
  tasks:  
  - name: Create a Docker group
    group:
      name: docker
      state: present
    become: yes      
      
  - name: Create an iSamples user account
    user: 
      name: isamples
      groups: docker
    become: yes
    
  - name: Install nginx
    apt:
      name: nginx
      state: present
    become: yes
    
  - name: Start nginx
    service:
      name: nginx
      state: started
  