---
- name: Configure an iSamples Development server
  hosts: all
  
  tasks:  
  - name: Create a Docker group
    group:
      name: docker
      state: present
    become: yes      
      
  - name: Create an iSamples user account
    user: 
      name: isamples
      groups: docker
    become: yes
    
  - name: Install nginx
    apt:
      name: nginx
      state: present
    become: yes
    
  - name: Start nginx
    service:
      name: nginx
      state: started
    become: yes      
      
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
    become: yes     

  - name: Install Docker dependencies
    apt:
      name:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
    become: yes
    notify: Install Docker and Docker compose
        
  - name: Start Docker
    service:
      name: docker
      state: started
      
  - name: Install iSamples in a Box service
    copy:
      src: ./isamples_inabox.service
      dest: /etc/systemd/system/isamples_inabox.service
    become: yes
    notify: Reload systemd
    
      
  - name: Install ACL packages for ansible to run its chmod as necessary
    apt:
      name:
        - acl
    become: yes    
    
  - name: Include the common role, which checks out and starts iSamples in a Box
    include_role:
      name: common    
  

  handlers:
    # Instructions gotten from https://docs.docker.com/engine/install/ubuntu/ and https://docs.docker.com/compose/cli-command/
  - name: Install Docker and Docker compose
    shell: cd ~ && curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh && mkdir -p /usr/local/lib/docker/cli-plugins &&  curl -SL https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-x86_64 -o /usr/local/lib/docker/cli-plugins/docker-compose && chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
    become: yes
    
  - name: Reload systemd
    systemd:
      daemon-reload: yes
    become: yes