---
- name: Configure plausible.io self-hosted solution on a server
  hosts: localhost
  connection: local
  become: yes
  
  tasks:
  - name: Download the plausible installation
    shell: "git clone https://github.com/plausible/hosting"
  
  - name: Check out the Plausible self-hosted repository
    git:
      repo: " https://github.com/plausible/hosting"
      dest: /home/isamples/plausible_hosting
      force: true
    become: yes
    become_method: sudo
    become_user: isamples
    
  - name: Generate the secret key
    shell: openssl rand -base64 64 | tr -d '\n' >> plausible-conf.env
    
  - name: Copy the plausible config to the plausible checkout directory
    copy:
      src: ./plausible-conf.env
      dest: /home/isamples/plausible_hosting
    become: yes
    become_method: sudo
    become_user: isamples      
    
  - name: Install plausible service
    copy:
      src: ./plausible_io.service
      dest: /etc/systemd/system/plausible_io.service
    notify: Reload systemd
    
  - name: Set up the certbot config in nginx
    shell: "certbot --nginx -d metricsaws.isample.xyz -m danny.mandel@gmail.com -n --agree-tos --redirect"