---
- name: Check out the iSamples Docker repository
  hosts: all
  
  vars_files:
    - vars/common_vars.yml
  
  tasks:
  - name: Check out iSamples Docker Repository
    git:
      repo: "https://github.com/isamplesorg/isamples_docker.git"
      version: "{{ latest_tag }}"
      track_submodules: no
      recursive: yes
      dest: /home/isamples/isamples_inabox
    become: yes
    become_method: sudo
    become_user: isamples
  
  - name: Restart iSamples Central
    service:
      name: isamples_central
      state: restarted
      enabled: yes
    become: yes