---
- name: Check out the iSamples Docker repository
  hosts: all
  
  tasks:
  - name: Check out iSamples Docker Repository
    git:
      repo: "https://github.com/isamplesorg/isamples_docker.git"
      version: "{{ latest_tag }}"
      track_submodules: no
      recursive: yes
      dest: /home/isamples/isamples_inabox
    become: yes
    become_method: sudo
    become_user: isamples
  
  - name: Restart iSamples Service
    service:
      name: "{{ item }}"
      state: restarted
      enabled: yes
    with_items:
      - "{{ services }}"
    become: yes