- name: Check out iSamples Docker Repository
  git:
    repo: "https://github.com/isamplesorg/isamples_docker.git"
    version: "{{ latest_tag }}"
    track_submodules: no
    recursive: yes
    dest: /home/isamples/isamples_inabox
  become: yes
  become_method: sudo
  become_user: isamples
  
- name: Lay down iSB config from template (if defined)
  template: 
    src: ../../../.env.isamples_inabox.j2
    dest: /home/isamples/isamples_inabox/.env.isamples_inabox
  when: hostname is defined

- name: Copy the local metadata models to git
  ansible.builtin.copy:
    src:  /var/local/data/models
    dest:  /home/isamples/isamples_inabox/isb/metadata_models
    remote_src: yes
  become: yes

- name: Restart iSamples Service
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - "{{ services }}"
  become: yes

- name: Cleanup metadata models directory
  file:
    state: absent
    path: /home/isamples/isamples_inabox/isb/metadata_models